### ISSUE TITLE
Shared library not loading

### ISSUE THREAD

**Issue by ozjongwon** [automerge/automerge-java#17] opened 2024-11-06 01:46 UTC
This is happening with Clojure(Leiningen) + Linux. After 'lein deps', the library file **libautomerge_jni.so** is in Clojure project's **target/native/x86_64-unknown-linux-gnu/**

In the AutomergeSys init phase, LoadLibrary looks for **libautomerge_jni_0_2_0.so**, and fails.

After renaming the file, it works.

**Comment by ozjongwon** [comment] 2024-11-06 07:25
The above description is not the whole story. At one point the copy method worked but not anymore.

I've looked further and realised the lib copied into /tmp directory. And after calling Document constructor, I confirmed so file and lck file were created in /tmp.

At this point, I believe the library loaded because calling System/load with the tmp lib file throws 'Execution error (UnsatisfiedLinkError) at jdk.internal.loader.NativeLibraries/loadLibrary (NativeLibraries.java:167).
Native Library /tmp/automerge-jni-0.0.1-9c1c5933-d878-4828-8d1d-cf7ad3185d2b-x86_64-unknown-linux-gnu.so already loaded in another classloader'.

Calling startTransaction is also fine. But reading static field  ObjectId.ROOT throws:

Execution error (ExceptionInInitializerError) at org.automerge.AutomergeSys/rootObjectId (AutomergeSys.java:-2).
Exception java.lang.UnsatisfiedLinkError: 'org.automerge.ObjectId org.automerge.AutomergeSys.rootObjectId()' [in thread "clojure-agent-send-off-pool-0"]

Any idea?

**Comment by alexjg** [comment] 2024-11-06 09:25
Do you have a small reproduction of the issue you could post here?

**Comment by ozjongwon** [comment] 2024-11-06 10:02
After adding init function call in Leiningen, now it works with the first option. 

It would be better adding libautomerge_jni_0_2_0.so rather than libautomerge_jni.so in automerge-0.0.7.jar, for example.
Then 'lein deps' will install it it under local target directory.

Thanks! (And feel free to close this one).

**Comment by alexjg** [comment] 2024-11-06 10:23
What do you mean by adding an init function call?

**Comment by ozjongwon** [comment] 2024-11-06 10:35
```
;; project.clj
  :repl-options {:init-ns crdt.automerge
                 :init (init-lib)}
```

```
;; (ns crdt.automerge)
(defn init-lib []
  (with-document-tx [doc tx]
    (with-text [text tx]
      (splice tx text "Hello World"))))
```

**Comment by alexjg** [comment] 2024-11-06 10:45
Oh I see the problem was only occurring in the REPL?

**Comment by ozjongwon** [comment] 2024-11-06 10:51
I don't know. I guess loading through different class loaders caused the issue, and I do not know much about class loader.

**Comment by alexjg** [comment] 2024-11-06 10:53
That's plausible. I'll close the issue then as you have a workaround. In a perfect world we would figure out a solution which doesn't require this init function on your part, but alas time is finite.

**Closed by alexjg** 2024-11-06 10:53 UTC
